{% set name = "iwopy" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FraunhoferIWES/iwopy/archive/v{{ version }}.tar.gz
  sha256: d38ce54f9f46d2c76c68d0b4a2c39d3a5e42ada2e2aebfea2eef5a44e95c8926

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python
    - matplotlib-base
    - numpy
    - scipy
  host:
    - python
    - pip
  run:
    - python
    - matplotlib-base
    - numpy
    - scipy

test:
  imports:
    - iwopy
  requires:
    - pip
    - pytest
    - pymoo
    - pygmo
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/FraunhoferIWES/iwopy
  summary: Fraunhofer IWES optimization tools in Python
  description: |
    The iwopy package is a meta package that provides interfaces to
    other open-source Python optimization packages out there. It can
    thus be understood as an attempt to provide the best of all worlds
    when it comes to solving optimization problems with Python. All 
    the credit for implementing the invoked optimizers goes to the
    original package providers.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - SchmJo
